package com.example.qlogserver.model;

import jakarta.persistence.*;
import java.time.OffsetDateTime;

/**
 * JPA Entity representing a single transaction record from the Quintiq logs.
 */
@Entity
@Table(name = "transaction_records", indexes = {
    @Index(name = "idx_transaction_start_time", columnList = "startTimeRaw"), // Index for time-based queries
    @Index(name = "idx_transaction_kind", columnList = "transactionKind"),
    @Index(name = "idx_transaction_status", columnList = "status"),
    @Index(name = "idx_transaction_context", columnList = "environmentContext") // New index for context
})
public class TransactionRecord {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long dbId; // Internal database ID

    // --- Context and Source Info ---
    @Column(length = 100, nullable = false)
    private String environmentContext; // New: Environment context (e.g., Prod_EU, Test_US)

    @Column(length = 100)
    private String agentId; // ID of the agent that sent this record

    @Column(length = 255)
    private String sourceLogFile; // Original CSV filename

    private Integer csvIndex; // Original line number in the CSV (approximate)

    // --- Core Transaction Info ---
    @Column(length = 50)
    private String transactionId;

    @Column(length = 50)
    private String transactionKind;

    @Column(length = 20)
    private String status;

    // Raw start/end times as strings (due to parsing ambiguity)
    @Column(length = 30)
    private String startTimeRaw;
    @Column(length = 30)
    private String endTimeRaw;

    // Parsed start/end times (if parsing is successful, otherwise null)
    // @Column(columnDefinition = "TIMESTAMP WITH TIME ZONE")
    // private OffsetDateTime startTime;
    // @Column(columnDefinition = "TIMESTAMP WITH TIME ZONE")
    // private OffsetDateTime endTime;

    // --- Timing Metrics (in milliseconds) ---
    private Double length;
    private Double waitingTime;
    private Double procTime;
    private Double funcTime;
    private Double dbTime;
    private Double streamTime;
    private Double kernelTime;
    private Double memoryCommitTime;
    private Double cleanupTime;
    private Double beginTime;
    private Double endTimeMetric; // Renamed from "end" to avoid SQL keyword conflict

    // --- Client Info ---
    @Column(length = 50)
    private String clientId;
    @Column(length = 100)
    private String username;
    @Column(length = 50)
    private String ipClient;
    @Column(length = 50)
    private String clientType;

    // --- Action Info ---
    @Column(length = 255)
    private String actionElementName;
    @Column(length = 100)
    private String actionElementType;
    @Column(length = 255)
    private String actionName;

    // --- Dataset Info ---
    @Column(length = 255)
    private String datasetName;
    private Integer datasetReadCount;
    private Integer datasetWriteCount;
    private Double datasetReadTime;
    private Double datasetWriteTime;

    // --- Resource Usage ---
    private Integer threadId;
    private Long memoryUsageStart;
    private Long memoryUsageEnd;
    private Integer objectsCreated;
    private Integer objectsDeleted;
    private Integer objectsUpdated;
    private Integer objectsRead;

    // --- Default Constructor (required by JPA) ---
    public TransactionRecord() {
    }

    // --- Getters and Setters (omitted for brevity, generated by IDE/Lombok) ---
    // ... Add all getters and setters ...


    public Long getDbId() {
        return dbId;
    }

    public void setDbId(Long dbId) {
        this.dbId = dbId;
    }

    public String getEnvironmentContext() {
        return environmentContext;
    }

    public void setEnvironmentContext(String environmentContext) {
        this.environmentContext = environmentContext;
    }

    public String getAgentId() {
        return agentId;
    }

    public void setAgentId(String agentId) {
        this.agentId = agentId;
    }

    public String getSourceLogFile() {
        return sourceLogFile;
    }

    public void setSourceLogFile(String sourceLogFile) {
        this.sourceLogFile = sourceLogFile;
    }

    public Integer getCsvIndex() {
        return csvIndex;
    }

    public void setCsvIndex(Integer csvIndex) {
        this.csvIndex = csvIndex;
    }

    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public String getTransactionKind() {
        return transactionKind;
    }

    public void setTransactionKind(String transactionKind) {
        this.transactionKind = transactionKind;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getStartTimeRaw() {
        return startTimeRaw;
    }

    public void setStartTimeRaw(String startTimeRaw) {
        this.startTimeRaw = startTimeRaw;
    }

    public String getEndTimeRaw() {
        return endTimeRaw;
    }

    public void setEndTimeRaw(String endTimeRaw) {
        this.endTimeRaw = endTimeRaw;
    }

    public Double getLength() {
        return length;
    }

    public void setLength(Double length) {
        this.length = length;
    }

    public Double getWaitingTime() {
        return waitingTime;
    }

    public void setWaitingTime(Double waitingTime) {
        this.waitingTime = waitingTime;
    }

    public Double getProcTime() {
        return procTime;
    }

    public void setProcTime(Double procTime) {
        this.procTime = procTime;
    }

    public Double getFuncTime() {
        return funcTime;
    }

    public void setFuncTime(Double funcTime) {
        this.funcTime = funcTime;
    }

    public Double getDbTime() {
        return dbTime;
    }

    public void setDbTime(Double dbTime) {
        this.dbTime = dbTime;
    }

    public Double getStreamTime() {
        return streamTime;
    }

    public void setStreamTime(Double streamTime) {
        this.streamTime = streamTime;
    }

    public Double getKernelTime() {
        return kernelTime;
    }

    public void setKernelTime(Double kernelTime) {
        this.kernelTime = kernelTime;
    }

    public Double getMemoryCommitTime() {
        return memoryCommitTime;
    }

    public void setMemoryCommitTime(Double memoryCommitTime) {
        this.memoryCommitTime = memoryCommitTime;
    }

    public Double getCleanupTime() {
        return cleanupTime;
    }

    public void setCleanupTime(Double cleanupTime) {
        this.cleanupTime = cleanupTime;
    }

    public Double getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(Double beginTime) {
        this.beginTime = beginTime;
    }

    public Double getEndTimeMetric() {
        return endTimeMetric;
    }

    public void setEndTimeMetric(Double endTimeMetric) {
        this.endTimeMetric = endTimeMetric;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getIpClient() {
        return ipClient;
    }

    public void setIpClient(String ipClient) {
        this.ipClient = ipClient;
    }

    public String getClientType() {
        return clientType;
    }

    public void setClientType(String clientType) {
        this.clientType = clientType;
    }

    public String getActionElementName() {
        return actionElementName;
    }

    public void setActionElementName(String actionElementName) {
        this.actionElementName = actionElementName;
    }

    public String getActionElementType() {
        return actionElementType;
    }

    public void setActionElementType(String actionElementType) {
        this.actionElementType = actionElementType;
    }

    public String getActionName() {
        return actionName;
    }

    public void setActionName(String actionName) {
        this.actionName = actionName;
    }

    public String getDatasetName() {
        return datasetName;
    }

    public void setDatasetName(String datasetName) {
        this.datasetName = datasetName;
    }

    public Integer getDatasetReadCount() {
        return datasetReadCount;
    }

    public void setDatasetReadCount(Integer datasetReadCount) {
        this.datasetReadCount = datasetReadCount;
    }

    public Integer getDatasetWriteCount() {
        return datasetWriteCount;
    }

    public void setDatasetWriteCount(Integer datasetWriteCount) {
        this.datasetWriteCount = datasetWriteCount;
    }

    public Double getDatasetReadTime() {
        return datasetReadTime;
    }

    public void setDatasetReadTime(Double datasetReadTime) {
        this.datasetReadTime = datasetReadTime;
    }

    public Double getDatasetWriteTime() {
        return datasetWriteTime;
    }

    public void setDatasetWriteTime(Double datasetWriteTime) {
        this.datasetWriteTime = datasetWriteTime;
    }

    public Integer getThreadId() {
        return threadId;
    }

    public void setThreadId(Integer threadId) {
        this.threadId = threadId;
    }

    public Long getMemoryUsageStart() {
        return memoryUsageStart;
    }

    public void setMemoryUsageStart(Long memoryUsageStart) {
        this.memoryUsageStart = memoryUsageStart;
    }

    public Long getMemoryUsageEnd() {
        return memoryUsageEnd;
    }

    public void setMemoryUsageEnd(Long memoryUsageEnd) {
        this.memoryUsageEnd = memoryUsageEnd;
    }

    public Integer getObjectsCreated() {
        return objectsCreated;
    }

    public void setObjectsCreated(Integer objectsCreated) {
        this.objectsCreated = objectsCreated;
    }

    public Integer getObjectsDeleted() {
        return objectsDeleted;
    }

    public void setObjectsDeleted(Integer objectsDeleted) {
        this.objectsDeleted = objectsDeleted;
    }

    public Integer getObjectsUpdated() {
        return objectsUpdated;
    }

    public void setObjectsUpdated(Integer objectsUpdated) {
        this.objectsUpdated = objectsUpdated;
    }

    public Integer getObjectsRead() {
        return objectsRead;
    }

    public void setObjectsRead(Integer objectsRead) {
        this.objectsRead = objectsRead;
    }
}

